Pgpool - improve postgres streaming Fixes #16

diff --git a/postgres/templates/postgresql/configmap-scripts.yaml b/postgres/templates/postgresql/configmap-scripts.yaml
--- a/postgres/templates/postgresql/configmap-scripts.yaml
+++ b/postgres/templates/postgresql/configmap-scripts.yaml
@@ -96,10 +96,82 @@ data:
 
     echo "[FAILOVER] Promotion timeout"
     exit 1
+  init-primary.sh: |
+    #!/bin/bash
+    set -euo pipefail
+
+    # This script check if pod was previously primary and if so, it will reinitialize the pod as a standby node.
+    # It's called by the postgres init container.
+    ORDINAL="${POD_NAME##*-}"
+    TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
+    NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
+    CA=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
+    API="https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/api/v1/namespaces/${NS}/pods"
+
+    SERVICE="{{ include "postgres.headlessName" . }}.$NS.svc.cluster.local"
+    IPS=$(nslookup "$SERVICE" 2>/dev/null | awk '/^Address: / {print $2}')
+    POD_EXISTS=0
+    echo "data" > {{ .Values.postgresql.persistence.mountPath }}/bootstrap-role
+
+    for ip in $IPS; do
+      if pg_isready -h "$ip" -U $POSTGRES_USER -d $POSTGRES_DB -p $POSTGRES_PORT >/dev/null 2>&1; then
+        POD_EXISTS=1
+      fi
+    done
+
+    # pod was a primary and other pods are ready then cleanup pgdata folder and reinitialize it
+    if { [ -f "$PGDATA/PG_VERSION" ] && [ ! -f "$PGDATA/standby.signal" ] && [ "$POD_EXISTS" = "1" ]; } then
+      echo "Previous primary pod detected and other pods are ready, cleaning up pgdata folder"
+      rm -rf $PGDATA/*
+      exit 0
+    fi
+
+    if { [ -f "$PGDATA/PG_VERSION" ] && [ ! -f "$PGDATA/standby.signal" ]; } || \
+        { [ ! -f "$PGDATA/PG_VERSION" ] && [ "$ORDINAL" = "0" ] && [ "$POD_EXISTS" = "0" ]; } 
+      then
+      echo "I am the Primary, then modifying pod labels to role=data-primary"
+      if wget -qO /dev/null \
+        --ca-certificate=$CA \
+        --header="Authorization: Bearer $TOKEN" \
+        --header="Content-Type: application/strategic-merge-patch+json" \
+        --method=PATCH --body-data='{"metadata":{"labels":{"role":"data-primary"}}}' \
+        "$API/$POD_NAME"
+      then
+        echo "data-primary" > {{ .Values.postgresql.persistence.mountPath }}/bootstrap-role
+        echo "Pod labels modified successfully"
+        exit 0
+      else
+        echo "Failed to modify pod labels"
+        exit 1
+      fi
+    else
+      echo "I am a Standby, waiting for primary to be ready..."
+      PRIMARY={{ include "postgres.primaryName" .}}.$NS.svc.cluster.local
+      until pg_isready -h "$PRIMARY" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -p $POSTGRES_PORT >/dev/null 2>&1 && \
+          psql -h "$PRIMARY" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -p $POSTGRES_PORT -tAc "SELECT 1" >/dev/null 2>&1; do
+        echo "Waiting for primary to be ready..."
+        sleep 5
+      done
+      echo "Primary is ready..."
+      exit 0
+    fi
+  init-replica.sh: |
+    #!/bin/bash
+    set -euo pipefail
+
+    if [ ! -f "$PGDATA/standby.signal" ]; then
+        echo "[INIT] Not a standby node, skipping initialization"
+        exit 0
+    fi
+
+    echo "[INIT] Initializing standby node..."
+    pg_basebackup -h $PRIMARY_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -D $PGDATA -Fp -Xs -P -R
+    echo "[INIT] Standby node initialized successfully"
   check-node-status.sh: |
     #!/bin/bash
     set -euo pipefail
 
+    # Check if the PostgreSQL server is ready and if the current pod is a standby node, check if it is registered in the pool nodes list.
     pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -p $POSTGRES_PORT >/dev/null 2>&1 || exit 1
     psql -U $POSTGRES_USER -d $POSTGRES_DB -p $POSTGRES_PORT -c "SELECT 1" >/dev/null 2>&1 || exit 1
 
