Pgpool - improve postgres streaming Fixes #16

diff --git a/postgres/templates/postgresql/configmap-scripts.yaml b/postgres/templates/postgresql/configmap-scripts.yaml
--- a/postgres/templates/postgresql/configmap-scripts.yaml
+++ b/postgres/templates/postgresql/configmap-scripts.yaml
@@ -14,6 +14,52 @@ metadata:
     {{- include "helper.labels.labels" . | nindent 4 }}
     app.kubernetes.io/component: pgpool
 data:
+  init-pgpool.sh: |
+    #!/bin/bash
+    set -euo pipefail
+
+    # This script watch for the primary node to be ready and then initialize the pgpool configuration files.
+
+    NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
+    PRIMARY={{ include "postgres.primaryName" .}}.$NS.svc.cluster.local
+    SVC={{ include "postgres.headlessName" .}}.$NS.svc.cluster.local
+    USER={{ .Values.pgpool.containerSecurityContext.runAsUser }}
+    GROUP={{ .Values.pgpool.containerSecurityContext.runAsGroup }}
+
+    echo "Waiting for primary to be ready..."
+    until pg_isready -h $PRIMARY -p $POSTGRES_PORT -d $POSTGRES_DB -U $POSTGRES_USER; do
+        echo "Waiting for primary to be ready..."
+        sleep 5
+    done
+    echo "Primary is ready..."
+
+    echo "Init data for pgpool"
+    mkdir -p $PGPOOL_DATA/conf $PGPOOL_DATA/logs $PGPOOL_DATA/run && \
+    chmod 750 $PGPOOL_DATA/conf $PGPOOL_DATA/logs $PGPOOL_DATA/run && \
+    chown -R $USER:$GROUP $PGPOOL_DATA/conf $PGPOOL_DATA/logs $PGPOOL_DATA/run
+
+    echo "Creating pcp.conf for pgpool..."
+    HASH=$(printf '%s' "$PGPOOL_PASSWORD" | md5sum | awk '{print $1}')
+    echo "# Generated by init container" > $PGPOOL_DATA/conf/pcp.conf
+    echo "${PGPOOL_USER}:${HASH}" >> $PGPOOL_DATA/conf/pcp.conf
+    echo "localhost:9898:${PGPOOL_USER}:${PGPOOL_PASSWORD}" > $PGPOOL_DATA/.pcppass
+    chown -R $USER:$GROUP $PGPOOL_DATA/conf/pcp.conf $PGPOOL_DATA/.pcppass
+    chmod 600 $PGPOOL_DATA/conf/pcp.conf $PGPOOL_DATA/.pcppass
+
+    echo "Creating backends.conf for pgpool..."
+    echo "# Generated by init container" > $PGPOOL_DATA/conf/backends.conf
+
+    for i in $(seq 0 {{ .Values.pgpool.maxBackendNodes }}); do
+      HOST=$(printf "{{ include "helper.names.fullname" . }}-%s" $i)
+      echo "backend_hostname${i} = '${HOST}.${SVC}'" >> $PGPOOL_DATA/conf/backends.conf
+      echo "backend_port${i} = ${POSTGRES_PORT}" >> $PGPOOL_DATA/conf/backends.conf
+      echo "backend_weight${i} = 1" >> $PGPOOL_DATA/conf/backends.conf
+      echo "backend_flag${i} = 'ALLOW_TO_FAILOVER'" >> $PGPOOL_DATA/conf/backends.conf
+      echo "backend_application_name${i} = '${HOST}'" >> $PGPOOL_DATA/conf/backends.conf
+    done
+
+    chown -R $USER:$GROUP $PGPOOL_DATA/conf/backends.conf
+    chmod 640 $PGPOOL_DATA/conf/backends.conf
   failover.sh: |
     #!/bin/bash
     set -euo pipefail
